from io import BytesIO
from datetime import datetime
import re

from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
)


def clean_ai_report(report):
    """
    Convert AI markdown output into PDF-friendly text.
    """

    report = re.sub(r"\*\*(.*?)\*\*", r"\1", report)
    report = report.replace("#", "")
    report = report.replace("* ", "• ")

    return report.strip()


def generate_pdf(kpis, report, forecast_df):

    buffer = BytesIO()

    doc = SimpleDocTemplate(
        buffer,
        topMargin=40,
        bottomMargin=40,
    )

    styles = getSampleStyleSheet()

    title_style = styles["Title"]
    heading_style = styles["Heading2"]
    normal_style = styles["BodyText"]
    footer_style = styles["Italic"]

    story = []

    # ======================================================
    # Title
    # ======================================================

    story.append(
        Paragraph(
            "<font size='24'><b>GemBiz Business Report</b></font>",
            title_style,
        )
    )

    story.append(
        Paragraph(
            datetime.now().strftime(
                "Generated on %d %B %Y, %I:%M %p"
            ),
            normal_style,
        )
    )

    story.append(Spacer(1, 20))

    # ======================================================
    # KPIs
    # ======================================================

    story.append(
        Paragraph(
            "Business KPIs",
            heading_style,
        )
    )

    story.append(Spacer(1, 8))

    story.append(
        Paragraph(
            f"""
            <b>Revenue</b> : Rs. {kpis['Revenue']:,.0f}<br/><br/>

            <b>Expenses</b> : Rs. {kpis['Expenses']:,.0f}<br/><br/>

            <b>Profit</b> : Rs. {kpis['Profit']:,.0f}<br/><br/>

            <b>Inventory</b> : {kpis['Inventory']} Units<br/><br/>

            <b>Health Score</b> : {kpis['Health Score']}/100
        """,
            normal_style,
        )
    )

    story.append(Spacer(1, 20))

    # ======================================================
    # AI Report
    # ======================================================

    story.append(
        Paragraph(
            "AI Business Report",
            heading_style,
        )
    )

    story.append(Spacer(1, 10))

    report = clean_ai_report(report)

    headings = [
        "Business Summary",
        "Strengths",
        "Weaknesses",
        "Risks",
        "Actionable Recommendations",
    ]

    for line in report.split("\n"):

        line = line.strip()

        if not line:
            story.append(Spacer(1, 8))
            continue

        if any(h in line for h in headings):

            story.append(
                Paragraph(
                    f"<b>{line}</b>",
                    heading_style,
                )
            )

            story.append(Spacer(1, 6))

        else:

            story.append(
                Paragraph(
                    line,
                    normal_style,
                )
            )

    story.append(Spacer(1, 20))

    # ======================================================
    # Forecast
    # ======================================================

    if forecast_df is not None:

        story.append(
            Paragraph(
                "Revenue Forecast",
                heading_style,
            )
        )

        story.append(Spacer(1, 8))

        avg = forecast_df["Predicted Revenue"].mean()

        trend = (
            "Increasing"
            if forecast_df.iloc[-1]["Predicted Revenue"]
            >
            forecast_df.iloc[0]["Predicted Revenue"]
            else "Decreasing"
        )

        story.append(
            Paragraph(
                f"""
<b>Expected Average Revenue</b> :
Rs. {avg:,.0f}<br/><br/>

<b>Business Trend</b> :
{trend}
""",
                normal_style,
            )
        )

    story.append(Spacer(1, 30))

    # ======================================================
    # Footer
    # ======================================================

    story.append(
        Paragraph(
            "Generated by GemBiz",
            footer_style,
        )
    )

    story.append(
        Paragraph(
            "AI-Powered Business Intelligence",
            footer_style,
        )
    )

    story.append(
        Paragraph(
            "Powered by Google Gemma",
            footer_style,
        )
    )

    doc.build(story)

    buffer.seek(0)

    return buffer